spring:
  server:
      port: 8081
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/learn
     username: root
     password: 28745zy!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true